 ## Problem Statement : Hospital Patient Data Analysis

## Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

Tasks:
1.	Load the patient dataset and show summary with info().

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
patient=pd.read_csv('Patient_Data.csv')
patient

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [3]:
patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [4]:
patient.columns

Index(['PatientID', 'Name', 'Department', 'Doctor', 'BillAmount',
       'ReceptionistID', 'CheckInTime'],
      dtype='object')

2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [5]:
patient_imp=patient[['PatientID', 'Department', 'Doctor', 'BillAmount']]
patient_imp.head()

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [6]:
patient_droped=patient.drop(['ReceptionistID', 'CheckInTime'],axis=1)
patient_droped

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

4.	Use groupby to find total bill amount per department.

In [7]:
patient['Department'].unique()

array(['Cardiology', 'Neurology', 'Orthopedics', 'Dermatology'],
      dtype=object)

In [8]:
patient['BillAmount'].unique()

array([5000.,   nan, 7500., 6200.])

In [9]:
department_total=patient.groupby('Department')['BillAmount'].sum()
department_total = department_total.sort_values(ascending=False)
print(department_total)

Department
Cardiology     16200.0
Orthopedics     7500.0
Dermatology        0.0
Neurology          0.0
Name: BillAmount, dtype: float64

5.	Remove duplicate patient records based on PatientID.

In [10]:
patientId_duplicate=patient[patient.duplicated(subset='PatientID')]
print(patientId_duplicate)


patient_cleaned=patient.drop_duplicates()
patient_cleaned

   PatientID   Name  Department     Doctor  BillAmount  ReceptionistID  \
5        101  Alice  Cardiology  Dr. Smith      5000.0               1

        CheckInTime
5  2023-01-10 09:00

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

6.	Fill missing BillAmount values with the mean bill amount.

In [11]:
patient['BillAmount'].isnull()

0    False
1     True
2    False
3    False
4     True
5    False
Name: BillAmount, dtype: bool

In [12]:
patient['BillAmount']=patient['BillAmount'].fillna(patient['BillAmount'].mean())

In [13]:
patient.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45

7.	Merge the billing dataset with patient dataset on PatientID.

In [14]:
billing=pd.read_csv('Billing_Data.csv')
billing.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [15]:
merged_data=pd.merge(patient_cleaned,billing,on='PatientID',how='inner')
merged_data

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45,1000,4000

8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [16]:
new_patients = pd.DataFrame({
    'PatientID':[106, 107],
    'Department':['Opthalmology', 'Urology'],
    'Doctor':['Dr. Neela', 'Dr. Naveen'],
    'BillAmount':[6500, 7200]
})

In [17]:
patient_up=pd.concat([patient_cleaned,new_patients],ignore_index=True)
patient_up

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1.0,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2.0,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1.0,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3.0,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2.0,2023-01-14 08:45
5,106,NaN,Opthalmology,Dr. Neela,6500.0,NaN,NaN
6,107,NaN,Urology,Dr. Naveen,7200.0,NaN,NaN

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [18]:
patient_up.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1.0,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2.0,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1.0,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3.0,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2.0,2023-01-14 08:45

In [19]:
new_billing_cols = pd.DataFrame({
    'InsuranceCovered': [True, False, True, True, False],
    'FinalAmount': [4500, 7200, 7000, 6000, 5800]
})

In [20]:
print(patient_up.shape)
print(new_billing_cols.shape)

(7, 7)
(5, 2)

In [21]:
new_billing_cols

   InsuranceCovered  FinalAmount
0              True         4500
1             False         7200
2              True         7000
3              True         6000
4             False         5800

In [22]:
patient_up=pd.concat([patient_up,new_billing_cols],axis=1)
patient_up

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1.0,2023-01-10 09:00,True,4500.0
1,102,Bob,Neurology,Dr. John,NaN,2.0,2023-01-11 10:30,False,7200.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1.0,2023-01-12 11:00,True,7000.0
3,104,David,Cardiology,Dr. Smith,6200.0,3.0,2023-01-13 12:00,True,6000.0
4,105,Eva,Dermatology,Dr. Rose,NaN,2.0,2023-01-14 08:45,False,5800.0
5,106,NaN,Opthalmology,Dr. Neela,6500.0,NaN,NaN,NaN,NaN
6,107,NaN,Urology,Dr. Naveen,7200.0,NaN,NaN,NaN,NaN